# Site settings
title: Mono
port: 3000
email: info@voltdata.info
description: > # Mono é um repositório de gráficos produzidos pela agência Volt Data Lab
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mono.voltdata.info" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Início', '/', 'fa-home']
  About : ['Sobre', '/sobre', 'fa-info']
  Contact : ['Contato', '/contato', 'fa-envelope-o']
  Author : ['Quem faz', '/quem', 'fa-users']
  Search: ['Explore', '/search', 'fa-search']
single_footer: '<p>Mono, por <a href="http://voltdata.info" target="_blank"> Volt Data Lab</a> - 2017 - <a href="/">gráficos recentes</a> </p>'
footer_links:
    About: ['Sobre o projeto', '/sobre']
    Writer: ['Quem faz', '/quem']


# Build settings
# markdown: kramdown
