# Site settings
title: Mono
email: info@voltdata.info
description: Mono é um repositório de gráficos produzidos pela agência Volt Data Lab
baseurl: '/grafico' # the subpath of your site, e.g. /blog
url: 'http://mono.voltdata.info/' # the base hostname & protocol for your site
permalink: /:categories/:title.html

# settings
markdown: kramdown
